### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hi! I'm ImgBot. Nice to meet you. 

I noticed there were a bunch of images living in your project that weren't totally optimized so I thought I'd make you a PR ;) I use a lossless compression algorithm from [ImageMagick](https://github.com/dlemstra/Magick.NET) so all the images are the same quality and dimensions as before only they take up less space now. 

Image processing is tough work, I know, but I never get tired and I never rest - not until all the images on GitHub are totally optimized.

*Total -- 1,207.25kb -> 1,175.32kb (2.64%)

/site/web/app/themes/sage/assets/images/blue_band.png -- 7.59kb -> 5.43kb (28.5%)
/site/web/app/themes/sage/assets/images/fiipregatit_favicon_32x32.png -- 0.80kb -> 0.74kb (8.38%)
/site/web/app/themes/sage/assets/images/logo-civictech.png -- 3.51kb -> 3.33kb (5.07%)
/site/web/app/themes/sage/assets/images/logo-civictech-small.png -- 3.82kb -> 3.65kb (4.37%)
/site/web/app/themes/sage/assets/images/fiipregatit_tabel_trusasupravietuire.jpg -- 100.05kb -> 96.39kb (3.66%)
/site/web/app/themes/sage/assets/images/share_fb_ghiduri.jpg -- 140.98kb -> 136.34kb (3.29%)
/site/web/app/themes/sage/assets/images/share_fb_campanii.jpg -- 184.08kb -> 179.28kb (2.61%)
/site/web/app/themes/sage/assets/images/share_fb_trusa.jpg -- 156.92kb -> 153.36kb (2.27%)
/site/web/app/themes/sage/assets/images/share_fb_default.jpg -- 139.64kb -> 136.60kb (2.18%)
/site/web/app/themes/sage/screenshot.png -- 254.83kb -> 249.35kb (2.15%)
/site/web/app/themes/sage/assets/images/header_small_img.jpg -- 215.03kb -> 210.84kb (1.95%)

### CODE REVIEW

**Comment by ionutpopacivictech** [comment]
Let's enroll him!

**Comment by dabutvin** [comment]
👍 happy to help

If you want more prs from ImgBot here, or any of your other projects, feel free to install the GitHub app.

https://github.com/apps/ImgBot

**Comment by ClaudiuCeia** [comment]
Hey man, thanks! Definitely will, ImgBot is the best :)

**Comment by cezarneaga** [comment]
Cute. :)

**Pull request merged**
